name: Deploy manually
on: workflow_dispatch
jobs:
  deploy_test:
    name: Deploy mnually to TEST
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Deploy release to test
        run: echo "Deploy release to test ${GITHUB_REF} / ${GITHUB_REF_NAME}"
      - name: Show URL
        run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${GITHUB_REF_NAME}/react-test-${GITHUB_REF_NAME/v}.tar.gz"
      - name: Download release archive
        run: curl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${GITHUB_REF_NAME}/react-test-${GITHUB_REF_NAME/v}.tar.gz" --location --output react-test.tar.gz
      - name: List
        run: ls -altr
      - name: Unarchive
        run: tar -xzf react-test.tar.gz
      - name: List
        run: ls -altr
