name: Deploy TEST
on:
  release:
    types: [published]
jobs:
  deploy_test:
    name: Deploy TEST
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Deploy release to test
        run: echo "Deploy release to test"
  deploy_prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Deploy release to prod
        run: echo "Deploy release to prod"