name: Deploy PROD
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy PROD
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Deploy release to prod
        run: echo "Deploy release to prod"