name: Deploy TEST
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy TEST
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Deploy release to test
        run: echo "Deploy release to test"